/**
 * Static utility for MIME type detection and extension mapping.
 * 
 * Centralizes MIME type logic previously duplicated across:
 * - MediaDownloaderService (ingestion-service)
 * - MtprotoMediaDownloader (backend)
 * - MediaController (ingestion-service)
 * - AdsMediaController (backend)
 * 
 * @example
 * ```ts
 * const ext = MimeTypeResolver.getExtensionFromMimeType('image/jpeg'); // '.jpg'
 * const mime = MimeTypeResolver.getMimeTypeFromExtension('.png'); // 'image/png'
 * ```
 */
export class MimeTypeResolver {
  /**
   * Mapping from MIME type to file extension.
   * Covers common image, video, and document types from Telegram.
   */
  private static readonly MIME_TO_EXTENSION: Record<string, string> = {
    // Images
    'image/jpeg': '.jpg',
    'image/jpg': '.jpg',
    'image/png': '.png',
    'image/gif': '.gif',
    'image/webp': '.webp',
    'image/svg+xml': '.svg',
    'image/bmp': '.bmp',
    
    // Videos
    'video/mp4': '.mp4',
    'video/mpeg': '.mpeg',
    'video/quicktime': '.mov',
    'video/x-msvideo': '.avi',
    'video/x-matroska': '.mkv',
    'video/webm': '.webm',
    
    // Documents
    'application/pdf': '.pdf',
    'application/zip': '.zip',
    'application/x-rar-compressed': '.rar',
    'text/plain': '.txt',
  };

  /**
   * Mapping from file extension to MIME type.
   * Generated by inverting MIME_TO_EXTENSION at runtime.
   */
  private static extensionToMime: Record<string, string> | null = null;

  /**
   * Get file extension from MIME type.
   * 
   * @param mimeType - MIME type (e.g., 'image/jpeg')
   * @returns File extension with leading dot (e.g., '.jpg'), or '.bin' if unknown
   * 
   * @example
   * ```ts
   * MimeTypeResolver.getExtensionFromMimeType('image/png'); // '.png'
   * MimeTypeResolver.getExtensionFromMimeType('unknown/type'); // '.bin'
   * ```
   */
  public static getExtensionFromMimeType(mimeType: string): string {
    if (!mimeType) {
      return '.bin';
    }
    
    const normalized = mimeType.toLowerCase().trim();
    return this.MIME_TO_EXTENSION[normalized] ?? '.bin';
  }

  /**
   * Get MIME type from file extension.
   * 
   * @param extension - File extension with or without leading dot
   * @returns MIME type string, or 'application/octet-stream' if unknown
   * 
   * @example
   * ```ts
   * MimeTypeResolver.getMimeTypeFromExtension('.jpg'); // 'image/jpeg'
   * MimeTypeResolver.getMimeTypeFromExtension('png'); // 'image/png'
   * MimeTypeResolver.getMimeTypeFromExtension('.unknown'); // 'application/octet-stream'
   * ```
   */
  public static getMimeTypeFromExtension(extension: string): string {
    if (!extension) {
      return 'application/octet-stream';
    }

    // Lazy-build reverse map on first use
    if (!this.extensionToMime) {
      this.extensionToMime = {};
      for (const [mime, ext] of Object.entries(this.MIME_TO_EXTENSION)) {
        this.extensionToMime[ext] = mime;
      }
    }

    // Normalize: ensure leading dot, lowercase
    const normalized = extension.startsWith('.') 
      ? extension.toLowerCase() 
      : `.${extension.toLowerCase()}`;

    return this.extensionToMime[normalized] ?? 'application/octet-stream';
  }

  /**
   * Detect MIME type from Telegram media metadata.
   * 
   * For photos, always returns 'image/jpeg' (Telegram default).
   * For documents, uses the mimeType field if present.
   * 
   * @param media - Telegram Api.MessageMedia object
   * @returns MIME type string, or null if cannot be determined
   */
  public static getMimeTypeFromTelegramMedia(media: any): string | null {
    if (!media) {
      return null;
    }

    // Photo messages are always JPEG in Telegram
    if (media.className === 'MessageMediaPhoto') {
      return 'image/jpeg';
    }

    // Documents carry their own MIME type
    if (media.className === 'MessageMediaDocument' && media.document?.mimeType) {
      return media.document.mimeType;
    }

    return null;
  }

  /**
   * Detect if a MIME type represents a video.
   * 
   * @param mimeType - MIME type string
   * @returns true if the MIME type is video/*
   */
  public static isVideo(mimeType: string | null): boolean {
    return mimeType?.startsWith('video/') ?? false;
  }

  /**
   * Detect if a MIME type represents an image.
   * 
   * @param mimeType - MIME type string
   * @returns true if the MIME type is image/*
   */
  public static isImage(mimeType: string | null): boolean {
    return mimeType?.startsWith('image/') ?? false;
  }
}
