import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * TypeORM persistence shape for `PromptTemplate`.
 *
 * Table: `crypto_news_publisher_prompt_templates` — user-defined LLM
 * prompt templates the crypto-news BC uses to refine matched
 * messages. Rows are managed via the future CRUD endpoint (T2);
 * this BC owns them. The `@Unique(name)` constraint enforces a
 * hard uniqueness rule across the table (name is the operator-facing
 * label).
 *
 * The `id` is generated by the domain layer
 * (`crypto.randomUUID()`) so the same id is visible to the API
 * without a roundtrip.
 *
 * NOTE: this is NOT the domain aggregate. The domain entity lives
 * at `telegram/crypto-news-publisher/domain/entities/prompt-template.entity.ts`
 * and owns invariants (length / range checks). The mapper
 * translates between the two so the domain stays pure.
 */
@Entity({ name: 'crypto_news_publisher_prompt_templates' })
@Index('uq_crypto_news_publisher_prompt_templates_name', ['name'], {
  unique: true,
})
export class PromptTemplateEntity {
  @PrimaryColumn({ name: 'id', type: 'uuid' })
  public id!: string;

  @Column({ name: 'name', type: 'varchar', length: 100 })
  public name!: string;

  @Column({ name: 'description', type: 'text', nullable: true })
  public description!: string | null;

  @Column({ name: 'model', type: 'varchar', length: 200 })
  public model!: string;

  @Column({ name: 'max_tokens', type: 'integer' })
  public maxTokens!: number;

  @Column({ name: 'temperature', type: 'double precision' })
  public temperature!: number;

  @Column({
    name: 'reasoning_effort',
    type: 'varchar',
    length: 16,
    nullable: true,
  })
  public reasoningEffort!: 'low' | 'medium' | 'high' | 'max' | null;

  @Column({ name: 'prompt_text', type: 'text' })
  public promptText!: string;

  @Column({ name: 'system_prompt_text', type: 'text', nullable: true })
  public systemPromptText!: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  public createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  public updatedAt!: Date;
}
